language: node_js
node_js:
 - "node"
env:
  global:
    - 'SFTP_USER=[user]'
    - 'SFTP_PASSWORD=[password]'
after_success:
- curl -globoff sftp://${SFTP_USER}:${SFTP_PASSWORD}@srchprty.com/public_html/
